// src/components/react/QRCode.tsx
/**
 * QRCode - Display M-Pesa Dynamic QR code
 * Pass base64 image from mpesa.qrCode() response
 */

export interface QRCodeProps {
  /** Base64 QR code image from Dynamic QR API */
  base64: string;
  alt?: string;
  size?: number;
  className?: string;
}

export function QRCode({
  base64,
  alt = "M-Pesa QR Code",
  size = 300,
  className = "",
}: QRCodeProps) {
  const src = base64.startsWith("data:")
    ? base64
    : `data:image/png;base64,${base64}`;

  return (
    <img
      src={src}
      alt={alt}
      width={size}
      height={size}
      className={`pesafy-qrcode ${className}`}
      loading="lazy"
    />
  );
}

// src/components/vue/QRCode.vue
<template>
  <img
    :src="qrSrc"
    :alt="alt"
    :width="size"
    :height="size"
    :class="['pesafy-qrcode', className]"
    loading="lazy"
  />
</template>

<script setup lang="ts">
import { computed } from "vue";

interface Props {
  base64: string;
  alt?: string;
  size?: number;
  className?: string;
}

const props = withDefaults(defineProps<Props>(), {
  alt: "M-Pesa QR Code",
  size: 300,
  className: "",
});

const qrSrc = computed(() => {
  return props.base64.startsWith("data:")
    ? props.base64
    : `data:image/png;base64,${props.base64}`;
});
</script>

<style scoped>
.pesafy-qrcode {
  display: block;
}
</style>
