// src/components/vue/PaymentStatus.vue
<template>
  <div
    v-if="status !== 'idle' || $slots.default"
    :class="[
      'pesafy-payment-status',
      `pesafy-payment-status--${status}`,
      className,
    ]"
    role="status"
    aria-live="polite"
  >
    <template v-if="status === 'pending'">
      <slot>{{ message || "Waiting for payment..." }}</slot>
    </template>
    <template v-else-if="status === 'success'">
      <slot>
        Payment successful
        <template v-if="transactionId"> ({{ transactionId }})</template>
        <template v-if="message"> - {{ message }}</template>
      </slot>
    </template>
    <template v-else-if="status === 'error'">
      <slot>
        Payment failed
        <template v-if="message"> - {{ message }}</template>
      </slot>
    </template>
    <slot v-else />
  </div>
</template>

<script setup lang="ts">
export type PaymentStatusState = "idle" | "pending" | "success" | "error";

interface Props {
  status: PaymentStatusState;
  message?: string;
  transactionId?: string;
  className?: string;
}

withDefaults(defineProps<Props>(), {
  className: "",
});
</script>

<style scoped>
.pesafy-payment-status {
  padding: 0.75rem 1rem;
  border-radius: 0.375rem;
  font-size: 0.875rem;
}

.pesafy-payment-status--pending {
  background: #fef3c7;
  color: #92400e;
}

.pesafy-payment-status--success {
  background: #d1fae5;
  color: #065f46;
}

.pesafy-payment-status--error {
  background: #fee2e2;
  color: #991b1b;
}
</style>

// src/components/react/PaymentStatus.tsx
/**
 * PaymentStatus - Display payment state (pending, success, failed)
 */

import type { ReactNode } from "react";

export type PaymentStatusState = "idle" | "pending" | "success" | "error";

export interface PaymentStatusProps {
  status: PaymentStatusState;
  /** Optional message for success/error states */
  message?: string;
  /** Optional transaction/callback data */
  transactionId?: string;
  children?: ReactNode;
  className?: string;
}

export function PaymentStatus({
  status,
  message,
  transactionId,
  children,
  className = "",
}: PaymentStatusProps) {
  if (status === "idle" && !children) return null;

  return (
    <div
      className={`pesafy-payment-status pesafy-payment-status--${status} ${className}`}
      role="status"
      aria-live="polite"
    >
      {status === "pending" &&
        (children ?? <span>Waiting for payment...</span>)}
      {status === "success" &&
        (children ?? (
          <span>
            Payment successful
            {transactionId && ` (${transactionId})`}
            {message && ` - ${message}`}
          </span>
        ))}
      {status === "error" &&
        (children ?? (
          <span>
            Payment failed
            {message && ` - ${message}`}
          </span>
        ))}
      {status === "idle" && children}
    </div>
  );
}
